import Head from 'next/head'
// import Image from 'next/image' 
// import styles from '../styles/Home.module.css'
import { useState } from 'react';
import { Header, Footer, CreateForm, ReportTable } from '../components';

export default function Home() {
  const [tabledata, setTableData] = useState([])

  function getUserInput(userInput) {
    setTableData([...tabledata, userInput])
    console.log(userInput)

  }
  function handleSubmit(e) {
    e.preventDefault();
    let locObj = {
      location: e.target.location.value,
      minimum_customers_per_hour: parseInt(e.target.mincust.value),
      maximum_customers_per_hour: parseInt(e.target.maxcust.value),
      average_cookies_per_sale: parseFloat(e.target.avgcookies.value),
    }
    // setdata([...data ,locObj]);
    setdata([locObj]);
  }


  return (
    <div className="">
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='mx-16 flex flex-col text-center'>
        <CreateForm getUserInput={getUserInput} />
        <ReportTable tabledata={tabledata} />


        {/* <div className="text-center text-gray-500 font-medium mt-16"> */}
        <h4>No Cookie Stands Available</h4>


        {/* </div> */}

      </main >

      <Footer />

    </div >
  )
}
