import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';


export default function Home() {
  const [data,setdata] = useState([])

  function handleSubmit(e) {
    e.preventDefault();
    let locObj = {
      location: e.target.location.value,
      minimum_customers_per_hour: parseInt(e.target.mincust.value),
      maximum_customers_per_hour: parseInt(e.target.maxcust.value),
      average_cookies_per_sale: parseFloat(e.target.avgcookies.value),
    }
    setdata([...data ,locObj]);
    // e.target.reset()
  }  

  return (
    <div className="">
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='text-2xl p-4 bg-green-500 text-gray-50'>
      <h1>
          Cookie Stand Admin
          </h1>

      </header>

      <main className='mx-16 flex flex-col text-center'>

        <form onSubmit={handleSubmit} className='my-6 px-4 bg-green-500 text-gray-50 rounded-lg'>
        <fieldset>
          <legend className='text-2xl py-4'>Create Cookie Stand</legend>
          <label>Location</label>
          <input name='location' className='w-1/2 text-blue-500 px-2' required />
          <br></br>
          <div className='inline-block px-2 py-6'>
            <label>Minimum Customers per Hour</label><br></br>
            <input name='mincust' type='number' required className='text-blue-500 px-2'/>
          </div>
          <div className='inline-block px-2 py-6'>
            <label>Maximum Customers per Hour</label><br></br>
            <input name='maxcust' type='number' required className='text-blue-500 px-2'/>
          </div>
          <div className='inline-block px-2 py-6'>
            <label>Average Cookies per Sale</label><br></br>
            <input name='avgcookies' type='number' placeholder="1.0" step="0.1" min="0" max="10" required className='text-blue-500 px-2'/>
          </div>
          <div className='inline-block px-2 py-6'>
            <button type='submit' className='bg-blue-400 px-8 rounded-lg'>Create</button>
          </div>
        </fieldset>
    </form>
    <div className="text-center text-gray-500 font-medium mt-16">
            <h4>Report Table Coming Soon...</h4>
            {
                data.map((item, index)=>{
                    return(
                        <p  key={index} className="mt-8"> {"{"}"location":"{item["location"]}",minCustomers":{item["minimum_customers_per_hour"]},maxCustomers":{item["maximum_customers_per_hour"]},"avgCookies":{item["average_cookies_per_sale"]}{"}"}</p>
                    )
                })
            }
           
        </div>

      </main>

      <footer className='p-4 bg-green-500 text-center text-gray-50'>
        <p>© 2022</p>
      </footer>

    </div>
  )
}
